---
spring:
  datasource:
    # url: jdbc:mysql://localhost:3306/app_test
    url: jdbc:postgresql://localhost:15432/app_test
    username: app_test
    hikari:
      maximum-pool-size: 1

logging:
  # config: classpath:logback-spring.xml
  file.name: api_test.log
  level:
    com.pwc: ${LOGGING_LEVEL_API:DEBUG}
